version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5173  # Set environment variable for backend API URL

  backend:
    build:
      context: ./backend
    ports:
      - "5173:5173"   # Map port 5173 on the host to port 5173 in the container
    environment:
      - NODE_ENV=production
      - PORT=5173      # Ensure the backend listens on port 5173
